<a href="https://colab.research.google.com/github/rohit-yup/Rohit_Kumar_Data-Science_and_Visualisation_Lab/blob/main/Rohit_Kumar_Assignment_4_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

#Section A

Que1.

In [ ]:
student_df=DataFrame({"Name":["Rahul","Aman","Ashi","Vikram"],"Age":[20,21,19,20],"City":["Mathura","Rishikesh","Roorkee","Bareilly"]})

Que2.

In [ ]:
print(student_df)

     Name  Age       City
0   Rahul   20    Mathura
1    Aman   21  Rishikesh
2    Ashi   19    Roorkee
3  Vikram   20   Bareilly

Que3.

In [ ]:
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

Que4.

In [ ]:
student_df.Name

0     Rahul
1      Aman
2      Ashi
3    Vikram
Name: Name, dtype: object

Que5.

In [ ]:
student_df['City']

0      Mathura
1    Rishikesh
2      Roorkee
3     Bareilly
Name: City, dtype: object

Que6.

In [ ]:
new_student_df=student_df[['Name','City']]
new_student_df

     Name       City
0   Rahul    Mathura
1    Aman  Rishikesh
2    Ashi    Roorkee
3  Vikram   Bareilly

Que7.

In [ ]:
book_df=DataFrame({"Book":["To Kill a Mockingbird","1984","The Great Gatsby","Pride and Prejudice"],"Author":["Harper Lee","George Orwell","F.Scott Fitzgerald","Jane Auston"],"Price":[149,119,142,88]})
book_df

                    Book              Author  Price
0  To Kill a Mockingbird          Harper Lee    149
1                   1984       George Orwell    119
2       The Great Gatsby  F.Scott Fitzgerald    142
3    Pride and Prejudice         Jane Auston     88

Que8.

In [ ]:
book_df['Publisher']="MybooksFactory"
book_df

                    Book              Author  Price       Publisher
0  To Kill a Mockingbird          Harper Lee    149  MybooksFactory
1                   1984       George Orwell    119  MybooksFactory
2       The Great Gatsby  F.Scott Fitzgerald    142  MybooksFactory
3    Pride and Prejudice         Jane Auston     88  MybooksFactory

Que9.

In [ ]:
df = DataFrame({"Sports":["Cricket","Football","Basketball","Rugby","Wrestling"]})
df["Serial No."]=np.arange(5)
df

       Sports  Serial No.
0     Cricket           0
1    Football           1
2  Basketball           2
3       Rugby           3
4   Wrestling           4

Que10.

In [ ]:
df=df.drop(columns=["Serial No."])
df

       Sports
0     Cricket
1    Football
2  Basketball
3       Rugby
4   Wrestling

Que11.

In [ ]:
movie_df=DataFrame({"Movie":["The Shawshan Redemption","The Godfather","The Dark Knight","Inception"],"Year":[1994,1972,2008,2010],"Rating":[9.3,9.2,9.1,8.8]})
movie_df

                     Movie  Year  Rating
0  The Shawshan Redemption  1994     9.3
1            The Godfather  1972     9.2
2          The Dark Knight  2008     9.1
3                Inception  2010     8.8

Que12.

In [ ]:
movie_df1=movie_df[["Movie","Rating"]]
movie_df1["Director"]=["Frank Darabont","Francis Ford Coppola","Christopher Nolan","Christopher Nolan"]
movie_df1

                     Movie  Rating              Director
0  The Shawshan Redemption     9.3        Frank Darabont
1            The Godfather     9.2  Francis Ford Coppola
2          The Dark Knight     9.1     Christopher Nolan
3                Inception     8.8     Christopher Nolan

Que13.

In [ ]:
s=Series(["Lucknow","Agra"],index=(0,3))
s

0    Lucknow
3       Agra
dtype: object

Que14.

In [ ]:
emp_df = DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya"],
    "Department": ["HR", "IT", "Finance", "Sales"],
    "Salary": [45000, 60000, 52000, 48000]
})
emp_df

  Employee Department  Salary
0     Amit         HR   45000
1     Neha         IT   60000
2    Rahul    Finance   52000
3    Priya      Sales   48000

In [ ]:
emp_df["Branch"]=s
emp_df

  Employee Department  Salary   Branch
0     Amit         HR   45000  Lucknow
1     Neha         IT   60000      NaN
2    Rahul    Finance   52000      NaN
3    Priya      Sales   48000     Agra

Que15.

In [65]:
copied_df=pd.read_clipboard()
copied_df

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

#Section B

Que16.

In [48]:
emp_df=DataFrame({
    "Employee": ["Amit", "Neha", "Rahul", "Priya","Srijan"],
    "Department": ["HR", "IT", "Finance", "Sales","Management"],
    "Experience": [4, 6, 5, 3,4]
})
emp_df

  Employee  Department  Experience
0     Amit          HR           4
1     Neha          IT           6
2    Rahul     Finance           5
3    Priya       Sales           3
4   Srijan  Management           4

In [52]:
emp_df1=emp_df[["Employee","Experience"]]
emp_df1

  Employee  Experience
0     Amit           4
1     Neha           6
2    Rahul           5
3    Priya           3
4   Srijan           4

Que17.

In [53]:
emp_df.Department

0            HR
1            IT
2       Finance
3         Sales
4    Management
Name: Department, dtype: object

In [57]:
emp_df.columns

Index(['Employee', 'Department', 'Experience', 'Office'], dtype='object')

Que18.

In [56]:
emp_df["Office"]="Head Office"
emp_df

  Employee  Department  Experience       Office
0     Amit          HR           4  Head Office
1     Neha          IT           6  Head Office
2    Rahul     Finance           5  Head Office
3    Priya       Sales           3  Head Office
4   Srijan  Management           4  Head Office

Que19.

In [58]:
emp_df["Office"]=np.arange(5)
emp_df

  Employee  Department  Experience  Office
0     Amit          HR           4       0
1     Neha          IT           6       1
2    Rahul     Finance           5       2
3    Priya       Sales           3       3
4   Srijan  Management           4       4

Que20.

In [60]:
Office_names=Series(["Delhi","Mumbai","Pune"],index=(0,2,4))
emp_df["Office"]=Office_names
emp_df

  Employee  Department  Experience  Office
0     Amit          HR           4   Delhi
1     Neha          IT           6     NaN
2    Rahul     Finance           5  Mumbai
3    Priya       Sales           3     NaN
4   Srijan  Management           4    Pune

Que21.

In [61]:
emp_df=emp_df.drop(columns=["Office"])
emp_df

  Employee  Department  Experience
0     Amit          HR           4
1     Neha          IT           6
2    Rahul     Finance           5
3    Priya       Sales           3
4   Srijan  Management           4

Que22.

In [67]:
product_df=DataFrame({"Product":["Amul Milk","Sparx","Vivo"],"Catgeory":["Dairy","Shoes","Phones"],"Price":[70,800,25000]})
product_df1=DataFrame({"Price":[70,800,25000],"Product":["Amul Milk","Sparx","Vivo"],"Catgeory":["Dairy","Shoes","Phones"]})

Que23.

In [69]:
new_cols_df = product_df.reindex(columns=["Product", "Catgeory", "Price", "Bonus"])
new_cols_df

     Product Catgeory  Price  Bonus
0  Amul Milk    Dairy     70    NaN
1      Sparx    Shoes    800    NaN
2       Vivo   Phones  25000    NaN

Que24.

In [72]:
marks_df = DataFrame({"Student Name":["Amit","Neha","Rahul","Priya"],"Total Marks":[450, 480, 420, 460]
})
marks_df["Total Marks"]

0    450
1    480
2    420
3    460
Name: Total Marks, dtype: int64

Que25.

In [73]:
copy=pd.read_clipboard()

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

#Section C

Que26.

In [74]:
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Course': ['Python', 'Data Science', 'Machine Learning', 'SQL', 'Web Dev'],
    'Score': [85, 92, 78, 88, 95]
}
course_df = pd.DataFrame(data)

In [75]:
print("Column Names:")
print(course_df.columns)

Column Names:
Index(['Student', 'Course', 'Score'], dtype='object')

In [79]:
student_col = course_df['Student']
print(student_col)

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Student, dtype: object

In [80]:
student_score_df = course_df[['Student', 'Score']]
print(student_score_df)

   Student  Score
0    Alice     85
1      Bob     92
2  Charlie     78
3    David     88
4      Eva     95

In [81]:
course_df['Batch'] = '2026-AG'
print(course_df)

   Student            Course  Score    Batch
0    Alice            Python     85  2026-AG
1      Bob      Data Science     92  2026-AG
2  Charlie  Machine Learning     78  2026-AG
3    David               SQL     88  2026-AG
4      Eva           Web Dev     95  2026-AG

Que27.

In [82]:
travel_df=DataFrame({
    "Destination": ["Goa", "Jaipur", "Manali", "Kerala", "Ooty"],
    "Mode": ["Flight", "Train", "Bus", "Flight", "Train"],
    "Days": [4, 3, 5, 6, 4]
})
travel_df

  Destination    Mode  Days
0         Goa  Flight     4
1      Jaipur   Train     3
2      Manali     Bus     5
3      Kerala  Flight     6
4        Ooty   Train     4

In [83]:
travel_df["Code"]=np.arange(5)
travel_df

  Destination    Mode  Days  Code
0         Goa  Flight     4     0
1      Jaipur   Train     3     1
2      Manali     Bus     5     2
3      Kerala  Flight     6     3
4        Ooty   Train     4     4

In [84]:
travel_df["Code"]=Series([101, 104], index=[1, 4])
travel_df

  Destination    Mode  Days   Code
0         Goa  Flight     4    NaN
1      Jaipur   Train     3  101.0
2      Manali     Bus     5    NaN
3      Kerala  Flight     6    NaN
4        Ooty   Train     4  104.0

Que28.

In [85]:
school_df=DataFrame({
    "Student": ["Amit", "Neha", "Rahul", "Priya", "Ashi"],
    "Class": ["10th", "10th", "12th", "11th", "12th"],
    "Section": ["A", "B", "A", "C", "B"]
})
school_df

  Student Class Section
0    Amit  10th       A
1    Neha  10th       B
2   Rahul  12th       A
3   Priya  11th       C
4    Ashi  12th       B

In [86]:
school_df_extended=school_df.reindex(columns=["Student", "Class", "Section", "House"])

In [87]:
school_df_extended["House"] = "Red"

In [88]:
school_df_extended

  Student Class Section House
0    Amit  10th       A   Red
1    Neha  10th       B   Red
2   Rahul  12th       A   Red
3   Priya  11th       C   Red
4    Ashi  12th       B   Red

Que29.

In [89]:
inventory_df=DataFrame({
    "Item": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
    "Category": ["Electronics", "Accessories", "Accessories", "Electronics", "Accessories"],
    "Stock": [15, 50, 40, 10, 25]
})
inventory_df

       Item     Category  Stock
0    Laptop  Electronics     15
1     Mouse  Accessories     50
2  Keyboard  Accessories     40
3   Monitor  Electronics     10
4   Headset  Accessories     25

In [90]:
inventory_df["Discount"]=Series([10, 15], index=[1, 3])
inventory_df

       Item     Category  Stock  Discount
0    Laptop  Electronics     15       NaN
1     Mouse  Accessories     50      10.0
2  Keyboard  Accessories     40       NaN
3   Monitor  Electronics     10      15.0
4   Headset  Accessories     25       NaN

In [91]:
inventory_df = inventory_df.drop(columns=["Discount"])
inventory_df

       Item     Category  Stock
0    Laptop  Electronics     15
1     Mouse  Accessories     50
2  Keyboard  Accessories     40
3   Monitor  Electronics     10
4   Headset  Accessories     25